ignore:
    - "**/mocks"
    - "**/buildDocFromHash.js"
    - "**/buildQuerySnapShot.js"
    - "**/home_page.js"
    - "**/TradePage.js"
    - "**/SearchPage.js"
    - "**/ViewItemTobeTraded.js"
    - "**/components"
    - "**/add_page.js"
    - "**/forgot_password.js"
    - "**/SignUpScreen.js"
    - "**/LoginScreen.js"

