version: 2.1

orbs:
  node: circleci/node@5.0.2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    # parameters:
    #    app-dir:
    #     type: string
    #     default: '~/SwapShop'
    #     description: Path to the directory containing your package.json file. Not needed if package.json lives in the root.
  
    executor: node/default
    # working_directory: ~/SwapShop
    steps:
      - checkout
         
      - node/install-packages:
          # app-dir:  ./SwapShop
          # cache-version: v1
          # cache-path: node_modules
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm build    
      - run:
          name: Run tests and collect coverage
          command: npm run test  
     
      - run:
          name: Upload coverage report to Codecov  
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB

workflows:
  
  build_and_test:
    jobs:
      -  build_and_test