version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build_and_test:
  
    executor: node/default
    working_directory: ./SwapShop
    steps:
      - checkout
         
      - node/install-packages:
          app-dir:  ./SwapShop
          cache-version: v1
          cache-path: node_modules
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm build    
      - run:
          name: Run tests and collect coverage
          command: npm run test  
     
      - run:
          name: Upload coverage report to Codecov  
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB

workflows:
  version: 2
  build_and_test:
    jobs:
      -  build_and_test