# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-package:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm build    
      - run:
          name: Run tests and collect coverage
          command: npm run test  
      - run:
          name: Upload coverage report to Codecov  
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB

workflows:
  swapshop:
    jobs:
      - build_and_test
      
