name: Tests
# on: [push, pull_request]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json


      - run: npm ci
      - run: npm run build --if-present

      - name: Running Jest tests
        run: npm test

      - name: Uploading coverage to Codecov
        uses: codecov/codecov-action@v2

  